### ISSUE TITLE
Ingresar ficha a un paciente mediante api client

### ISSUE THREAD

**Issue by bryanfaundez** [bryanfaundez/Ficha_Medica#1]
{
"error": {
"statusCode": 500,
"name": "Error",
"message": "Invalid JSON data. Found a value that is not a string: 1052412990 for relationship RelationshipDeclaration {name=paciente, type=org.ficha.life.Paciente, array=false, optional=false}",
"stack": "Error: Invalid JSON data. Found a value that is not a string: 1052412990 for relationship RelationshipDeclaration {name=paciente, type=org.ficha.life.Paciente, array=false, optional=false} at JSONPopulator.visitRelationshipDeclaration (/Users/bryanfaundez/.nvm/versions/node/v8.11.4/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/serializer/jsonpopulator.js:289:27) at JSONPopulator.visit (/Users/bryanfaundez/.nvm/versions/node/v8.11.4/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/serializer/jsonpopulator.js:98:25) at RelationshipDeclaration.accept (/Users/bryanfaundez/.nvm/versions/node/v8.11.4/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/introspect/decorated.js:65:24) at properties.forEach (/Users/bryanfaundez/.nvm/versions/node/v8.11.4/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/serializer/jsonpopulator.js:124:51) at Array.forEach (<anonymous>) at JSONPopulator.visitClassDeclaration (/Users/bryanfaundez/.nvm/versions/node/v8.11.4/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/serializer/jsonpopulator.js:120:20) at JSONPopulator.visit (/Users/bryanfaundez/.nvm/versions/node/v8.11.4/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/serializer/jsonpopulator.js:96:25) at AssetDeclaration.accept (/Users/bryanfaundez/.nvm/versions/node/v8.11.4/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/introspect/decorated.js:65:24) at Serializer.fromJSON (/Users/bryanfaundez/.nvm/versions/node/v8.11.4/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/serializer.js:180:26) at ensureConnected.then (/Users/bryanfaundez/.nvm/versions/node/v8.11.4/lib/node_modules/composer-rest-server/node_modules/loopback-connector-composer/lib/businessnetworkconnector.js:635:43) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)"
}
}

**Comment by bryanfaundez** [comment]
El problema fue que el código primario que vincula la ficha medica con el paciente es tipo de datos string y ingresamos un entero como "rut" y al buscar ese código con la apli client este no reconocía el tipo de datos por cual cual fue solucionado agregado comillas al rut para hacerlo string 
Ejemplo "19338404" ya con eso no genera problemas
